spring.application.name=esimene_kontrolltoo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/esimene_kontrolltoo
spring.datasource.username=postgres
spring.datasource.password=root
